name=Test
group=com.template
version=0.1
kotlin.incremental=false
corda_release_group=net.corda
corda_release_version=4.12.10
corda_gradle_plugins_version=5.1.1
aetherVersion=1.0.0.v20140518
maven_resolver_version=1.1.1
junit_version=4.12
dokka_version=0.9.17
artifactoryContextUrl=https://software.r3.com/artifactory
kotlin_version=1.9.0
persistence_version=2.2
typesafe_config_version=1.4.3
guava_version=33.1.0-jre
quasar_version=0.9.0_r3